### ISSUE TITLE
credenciais para os bancos de dados

### ISSUE THREAD

**Issue by pauloFernandes** [Joaopdev/Inventario-Raro#30]
seguem abaixo as credenciais para os bancos de dados que poderão ser utilizados no trabalho final. O banco `_prod` será o avaliado na entrega do projeto.

```yaml
host: 3.221.159.196
port: 3320
user: 'undefined_user'
password: 'WBUVfFVB9BBFBRWz'
databases:
  undefined_inventario_dev
  undefined_inventario_hml
  undefined_inventario_prod
```
